// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snail_ai_grpc_service.proto

// Protobuf Java Version: 3.25.5
package com.aizuda.snail.ai.common.grpc.auto;

public interface GrpcSnailAiResultOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcSnailAiResult)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>int32 status = 2;</code>
   * @return The status.
   */
  int getStatus();

  /**
   * <code>string message = 3;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 3;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();

  /**
   * <code>string data = 4;</code>
   * @return The data.
   */
  String getData();
  /**
   * <code>string data = 4;</code>
   * @return The bytes for data.
   */
  com.google.protobuf.ByteString
      getDataBytes();
}
