// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snail_ai_grpc_service.proto

// Protobuf Java Version: 3.25.5
package com.aizuda.snail.ai.common.grpc.auto;

public interface GrpcSnailAiRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:GrpcSnailAiRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 reqId = 1;</code>
   * @return The reqId.
   */
  long getReqId();

  /**
   * <code>.Metadata metadata = 2;</code>
   * @return Whether the metadata field is set.
   */
  boolean hasMetadata();
  /**
   * <code>.Metadata metadata = 2;</code>
   * @return The metadata.
   */
  Metadata getMetadata();
  /**
   * <code>.Metadata metadata = 2;</code>
   */
  MetadataOrBuilder getMetadataOrBuilder();

  /**
   * <code>string body = 3;</code>
   * @return The body.
   */
  String getBody();
  /**
   * <code>string body = 3;</code>
   * @return The bytes for body.
   */
  com.google.protobuf.ByteString
      getBodyBytes();
}
