// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: snail_ai_grpc_service.proto

// Protobuf Java Version: 3.25.5
package com.aizuda.snail.ai.common.grpc.auto;

public final class SnailAiGrpcService {
  private SnailAiGrpcService() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcSnailAiRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcSnailAiRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_GrpcSnailAiResult_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_GrpcSnailAiResult_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Metadata_HeadersEntry_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Metadata_HeadersEntry_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\033snail_ai_grpc_service.proto\"N\n\022GrpcSna" +
      "ilAiRequest\022\r\n\005reqId\030\001 \001(\003\022\033\n\010metadata\030\002" +
      " \001(\0132\t.Metadata\022\014\n\004body\030\003 \001(\t\"Q\n\021GrpcSna" +
      "ilAiResult\022\r\n\005reqId\030\001 \001(\003\022\016\n\006status\030\002 \001(" +
      "\005\022\017\n\007message\030\003 \001(\t\022\014\n\004data\030\004 \001(\t\"p\n\010Meta" +
      "data\022\013\n\003uri\030\003 \001(\t\022\'\n\007headers\030\007 \003(\0132\026.Met" +
      "adata.HeadersEntry\032.\n\014HeadersEntry\022\013\n\003ke" +
      "y\030\001 \001(\t\022\r\n\005value\030\002 \001(\t:\0028\001B(\n$com.aizuda" +
      ".snail.ai.common.grpc.autoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_GrpcSnailAiRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_GrpcSnailAiRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcSnailAiRequest_descriptor,
        new String[] { "ReqId", "Metadata", "Body", });
    internal_static_GrpcSnailAiResult_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_GrpcSnailAiResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_GrpcSnailAiResult_descriptor,
        new String[] { "ReqId", "Status", "Message", "Data", });
    internal_static_Metadata_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Metadata_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_descriptor,
        new String[] { "Uri", "Headers", });
    internal_static_Metadata_HeadersEntry_descriptor =
      internal_static_Metadata_descriptor.getNestedTypes().get(0);
    internal_static_Metadata_HeadersEntry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Metadata_HeadersEntry_descriptor,
        new String[] { "Key", "Value", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
